services:
  docs:
    build:
      context: https://github.com/jonas99-pixel/vuetify-docs.git
      dockerfile: Dockerfile
    image: vuetify-docs:latest
    restart: unless-stopped
    ports:
      -"8095:80"
    networks:
      macvlan_net:
        ipv4_address: 10.220.0.101

networks:
  macvlan_net:
    external: true