services:
  docs:
    build:
      context: https://github.com/DEIN_USER/vuetify-docs.git#main
      dockerfile: Dockerfile
    image: vuetify-docs:latest
    restart: unless-stopped
    ports:
      - "${PORT:-8095}:80"
    networks:
      macvlan_net:
        ipv4_address: 10.220.0.101

networks:
  macvlan_net:
    external: true